name: Custom Monitoring

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run custom monitor script for EBI Public HTTP
        run: |
          ./monitor.sh http://ftp.ebi.ac.uk/robots.txt

      - name: Run custom monitor script for EBI Public HTTPS
        run: |
          ./monitor.sh https://ftp.ebi.ac.uk/robots.txt

      - name: Run custom monitor script for EBI Public FTP
        run: |
          ./monitor.sh ftp://ftp.ebi.ac.uk/robots.txt

      - name: Run custom monitor script for Wikipedia
        run: |
          ./monitor.sh https://en.wikipedia.org/robots.txt

      - name: Run custom monitor script for Hacker News
        run: |
          ./monitor.sh https://news.ycombinator.com/robots.txt

